'use strict';

const express  = require('express');
const { isAuthenticated } = require('../middleware/auth');
const { getPool, sql }    = require('../config/database');
const router = express.Router();

router.get('/', isAuthenticated, async (req, res, next) => {
  try {
    const pool = await getPool();

    const [countsResult, recentLogsResult, upcomingPMsResult, repairsFollowUpResult] = await Promise.all([
      // Summary counts
      pool.request().query(`
        SELECT
          (SELECT COUNT(*) FROM Sites WHERE IsActive = 1) AS Sites,
          (SELECT COUNT(*) FROM Inventory i
           JOIN InventoryStatuses s ON s.StatusID = i.StatusID
           WHERE i.IsActive = 1 AND i.TrackingType = 'serialized' AND s.StatusName = 'In-Stock')
          +
          (SELECT ISNULL(SUM(qa), 0) FROM (
             SELECT i.QuantityTotal - ISNULL((
               SELECT SUM(si.Quantity) FROM SiteInventory si
               WHERE si.ItemID = i.ItemID AND si.RemovedAt IS NULL
             ), 0) AS qa
             FROM Inventory i
             WHERE i.IsActive = 1 AND i.TrackingType = 'bulk'
           ) AS _bulk) AS InventoryInStock,
          (SELECT COUNT(*) FROM RepairTracking WHERE ReceivedDate IS NULL) AS OpenRepairs,
          (SELECT COUNT(*) FROM PMSchedules pm
           WHERE pm.IsActive = 1
             AND (pm.LastPerformedAt IS NULL
               OR DATEADD(DAY, pm.FrequencyDays, pm.LastPerformedAt) <= DATEADD(DAY, 14, GETUTCDATE()))
          ) AS PMsDue
      `),

      // Recent log entries (last 8, non-auto-generated)
      pool.request().query(`
        SELECT TOP 8 le.LogEntryID, le.SiteID, le.EntryDate, le.Subject,
               s.SiteName, lt.TypeName,
               COALESCE(u.DisplayName, le.PerformedBy) AS PerformedByName
        FROM LogEntries le
        JOIN Sites s     ON s.SiteID      = le.SiteID
        JOIN LogTypes lt ON lt.LogTypeID  = le.LogTypeID
        LEFT JOIN Users u ON u.UserID     = le.PerformedByUserID
        WHERE le.IsAutoGenerated = 0
        ORDER BY le.EntryDate DESC, le.CreatedAt DESC
      `),

      // Upcoming PMs due within 30 days or overdue
      pool.request().query(`
        SELECT TOP 5 pm.ScheduleID, pm.SiteID, pm.Title,
               s.SiteName,
               u.DisplayName AS AssignedToName,
               DATEDIFF(day, GETUTCDATE(),
                 CASE WHEN pm.LastPerformedAt IS NULL THEN GETUTCDATE()
                      ELSE DATEADD(DAY, pm.FrequencyDays, pm.LastPerformedAt) END
               ) AS DaysUntilDue
        FROM PMSchedules pm
        JOIN Sites s ON s.SiteID = pm.SiteID
        LEFT JOIN Users u ON u.UserID = pm.AssignedUserID
        WHERE pm.IsActive = 1
          AND (pm.LastPerformedAt IS NULL
               OR DATEADD(DAY, pm.FrequencyDays, pm.LastPerformedAt) <= DATEADD(DAY, 30, GETUTCDATE()))
        ORDER BY DaysUntilDue ASC
      `),

      // Repairs with follow-up due today or overdue
      pool.request().query(`
        SELECT TOP 5 rt.RepairID, i.SerialNumber, rt.FollowUpDate
        FROM RepairTracking rt
        JOIN Inventory i ON i.ItemID = rt.ItemID
        WHERE rt.ReceivedDate IS NULL
          AND rt.FollowUpDate IS NOT NULL
          AND rt.FollowUpDate <= GETUTCDATE()
        ORDER BY rt.FollowUpDate ASC
      `),
    ]);

    const c = countsResult.recordset[0];
    res.render('dashboard/index', {
      title: 'Dashboard',
      counts: {
        sites:            c.Sites,
        inventoryInStock: c.InventoryInStock,
        openRepairs:      c.OpenRepairs,
        pmsDue:           c.PMsDue,
      },
      recentLogs:      recentLogsResult.recordset,
      upcomingPMs:     upcomingPMsResult.recordset,
      repairsFollowUp: repairsFollowUpResult.recordset,
    });
  } catch (err) { next(err); }
});

module.exports = router;
