-- =============================================================================
-- SiteMaintenance Seed Data
-- Run AFTER schema.sql. Inserts default lookup values and the initial admin user.
-- Change the admin password after first login.
-- =============================================================================

-- ============================================================
-- ROLES
-- ============================================================
INSERT INTO Roles (RoleName, Description) VALUES
    ('Admin',              'Full access: all CRUD, user management, settings, audit log'),
    ('Technician',         'Create/edit log entries, install/remove inventory, upload files, view all'),
    ('Contractor',         'Create log entries for assigned sites, upload files, view assigned sites'),
    ('Viewer',             'Read-only: view sites, inventory, logs, and documents'),
    ('Maintenance',        'Create, edit, close, and delete maintenance items'),
    ('Maintenance-Close',  'Close maintenance items assigned to them; view only their own items'),
    ('SystemKeys',         'Can create and manage system keys'),
    ('Notifications',      'Can manage personal email notification preferences'),
    ('ImportExport',       'Can import and export data for Sites, Inventory, System Keys, and Vendors'),
    ('NetworkMapUpdater',  'Can view sites and manage Network Resources (add/edit/delete devices and import/export network resources). Cannot delete sites or access other admin areas.');

-- ============================================================
-- SITE STATUSES
-- ============================================================
INSERT INTO SiteStatuses (StatusName) VALUES
    ('Current'),
    ('Maintenance'),
    ('Past-Due');

-- ============================================================
-- INVENTORY STATUSES
-- ============================================================
INSERT INTO InventoryStatuses (StatusName) VALUES
    ('In-Stock'),
    ('Deployed'),
    ('In-Repair'),
    ('Checked-Out'),
    ('Retired');

-- ============================================================
-- MAINTENANCE TYPES
-- ============================================================
INSERT INTO MaintenanceTypes (TypeName) VALUES
    ('Inspection'),
    ('Repair'),
    ('Upgrade'),
    ('Configuration'),
    ('Other');

-- ============================================================
-- LOG TYPES
-- ============================================================
INSERT INTO LogTypes (TypeName, IsAutomatic) VALUES
    ('Preventive Maintenance', 0),
    ('Corrective Maintenance', 0),
    ('Contractor Work',        0),
    ('Technician Work',        0),
    ('General Note',           0),
    ('Site Inspection',        0),
    ('Inventory Change',       1);  -- IsAutomatic = auto-generated by system

-- ============================================================
-- DEFAULT SITE TYPES
-- ============================================================
INSERT INTO SiteTypes (TypeName, Description) VALUES
    ('Primary',  'Primary or main site'),
    ('Secondary','Secondary or backup site'),
    ('Remote',   'Remote or edge location'),
    ('Hub',      'Hub or distribution point');

-- ============================================================
-- DEFAULT INVENTORY CATEGORIES
-- ============================================================
INSERT INTO InventoryCategories (CategoryName, Description) VALUES
    ('Hardware',    'Physical hardware components'),
    ('Networking',  'Network equipment and accessories'),
    ('Power',       'Power supplies, UPS, batteries'),
    ('Cabling',     'Cables, connectors, patch panels'),
    ('Other',       'Miscellaneous items');

-- ============================================================
-- DEFAULT STOCK LOCATION
-- ============================================================
INSERT INTO StockLocations (LocationName, Description) VALUES
    ('Main Warehouse', 'Primary inventory storage location');

-- ============================================================
-- APP SETTINGS (auth and email — values empty, set via admin UI or .env)
-- ============================================================
INSERT INTO AppSettings (SettingKey, SettingValue, Description) VALUES
    -- OIDC / Entra ID
    ('oidc.enabled',      '0',   'Enable OIDC / Entra ID login (1=enabled, 0=disabled)'),
    ('oidc.clientId',     NULL,  'Entra ID Application (client) ID'),
    ('oidc.clientSecret', NULL,  'Entra ID client secret'),
    ('oidc.tenantId',     NULL,  'Entra ID Directory (tenant) ID'),
    ('oidc.redirectUri',  NULL,  'Redirect URI registered in Entra ID (e.g. https://yourapp/auth/oidc/callback)'),
    -- LDAP / Active Directory
    ('ldap.enabled',      '0',   'Enable LDAP / AD login (1=enabled, 0=disabled)'),
    ('ldap.url',          NULL,  'LDAP server URL (e.g. ldap://dc.example.com:389)'),
    ('ldap.bindDn',       NULL,  'Service account DN used to bind (e.g. CN=svc,OU=SvcAccts,DC=example,DC=com)'),
    ('ldap.bindCredentials', NULL, 'Service account password'),
    ('ldap.searchBase',   NULL,  'Search base DN (e.g. OU=Users,DC=example,DC=com)'),
    ('ldap.searchFilter', NULL,  'Search filter (e.g. (sAMAccountName={{username}}))'),
    -- Email / SMTP
    ('email.enabled',             '0',    'Enable outbound email notifications (1=enabled, 0=disabled)'),
    ('email.host',                NULL,   'SMTP host (e.g. smtp.office365.com)'),
    ('email.port',                '587',  'SMTP port'),
    ('email.secure',              '0',    'Use TLS (1=true, 0=false — use STARTTLS for port 587)'),
    ('email.user',                NULL,   'SMTP authentication username'),
    ('email.password',            NULL,   'SMTP authentication password'),
    ('email.fromAddress',         NULL,   'From address for outbound emails'),
    ('email.fromName',            'SiteMaintenance', 'From display name for outbound emails'),
    -- Notification thresholds
    ('email.pmReminderDays',       '14',  'Days before PM due date to send reminder'),
    ('email.warrantyReminderDays', '30',  'Days before warranty expiry to send reminder'),
    ('email.checkoutReminderDays', '30',  'Days an item can be checked out before sending reminder');

-- ============================================================
-- INITIAL ADMIN USER
-- Password: Admin@1234  (bcrypt hash — change after first login)
-- To generate your own: node -e "const b=require('bcryptjs');console.log(b.hashSync('YourPassword',12))"
-- ============================================================
INSERT INTO Users (Username, DisplayName, Email, PasswordHash, AuthProvider, IsActive)
VALUES (
    'admin',
    'System Administrator',
    'admin@localhost',
    '$2a$12$kiZrm9K9lWU3y4Ke6tp0m.lVR9NPPYg0tIpWXBgWUHY1Om1foPFmy',
    'local',
    1
);

-- Assign Admin role to the initial admin user
INSERT INTO UserRoles (UserID, RoleID)
SELECT u.UserID, r.RoleID
FROM Users u, Roles r
WHERE u.Username = 'admin' AND r.RoleName = 'Admin';
