'use strict';

const { getPool, sql } = require('../config/database');
const { writeAudit }   = require('./auditModel');

async function getBySite(siteID, { logTypeID, dateFrom, dateTo, page = 1, pageSize = 25 } = {}) {
  const pool = await getPool();
  const request = pool.request();
  const conditions = ['le.SiteID = @SiteID'];
  request.input('SiteID', sql.Int, siteID);

  if (logTypeID) {
    conditions.push('le.LogTypeID = @LogTypeID');
    request.input('LogTypeID', sql.Int, logTypeID);
  }
  if (dateFrom) {
    conditions.push('le.EntryDate >= @DateFrom');
    request.input('DateFrom', sql.Date, new Date(dateFrom));
  }
  if (dateTo) {
    conditions.push('le.EntryDate <= @DateTo');
    request.input('DateTo', sql.Date, new Date(dateTo));
  }

  const where = conditions.join(' AND ');
  const offset = (page - 1) * pageSize;
  request.input('Offset',   sql.Int, offset);
  request.input('PageSize', sql.Int, pageSize);

  const countReq = pool.request().input('SiteID', sql.Int, siteID);
  if (logTypeID) countReq.input('LogTypeID', sql.Int,  logTypeID);
  if (dateFrom)  countReq.input('DateFrom',  sql.Date, new Date(dateFrom));
  if (dateTo)    countReq.input('DateTo',    sql.Date, new Date(dateTo));

  const countResult = await countReq.query(`SELECT COUNT(*) AS Total FROM LogEntries le WHERE ${where}`);
  const total = countResult.recordset[0].Total;

  const result = await request.query(`
    SELECT
      le.LogEntryID, le.SiteID, le.LogTypeID, le.EntryDate,
      le.PerformedBy, le.PerformedByUserID, le.Subject, le.Description,
      le.Notes, le.IsAutoGenerated, le.CreatedByUserID, le.CreatedAt,
      lt.TypeName,
      lt.TypeName    AS LogTypeName,
      pb.DisplayName AS PerformedByUserName,
      cb.DisplayName AS CreatedByName
    FROM LogEntries le
    LEFT JOIN LogTypes lt ON lt.LogTypeID = le.LogTypeID
    LEFT JOIN Users    pb ON pb.UserID    = le.PerformedByUserID
    LEFT JOIN Users    cb ON cb.UserID    = le.CreatedByUserID
    WHERE ${where}
    ORDER BY le.EntryDate DESC, le.LogEntryID DESC
    OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY
  `);

  return { rows: result.recordset, total, page, pageSize, totalPages: Math.ceil(total / pageSize) };
}

async function getByID(logEntryID) {
  const pool = await getPool();
  const result = await pool.request()
    .input('LogEntryID', sql.Int, logEntryID)
    .query(`
      SELECT
        le.LogEntryID, le.SiteID, le.LogTypeID, le.EntryDate,
        le.PerformedBy, le.PerformedByUserID, le.Subject, le.Description,
        le.Notes, le.IsAutoGenerated, le.CreatedByUserID, le.CreatedAt,
        CASE WHEN s.ParentSiteID IS NOT NULL
             THEN ps.SiteName + ' / ' + s.SiteName
             ELSE s.SiteName END AS SiteName,
        lt.TypeName    AS LogTypeName,
        pb.DisplayName AS PerformedByUserName,
        cb.DisplayName AS CreatedByName
      FROM LogEntries le
      LEFT JOIN Sites    s  ON s.SiteID    = le.SiteID
      LEFT JOIN Sites    ps ON ps.SiteID   = s.ParentSiteID
      LEFT JOIN LogTypes lt ON lt.LogTypeID = le.LogTypeID
      LEFT JOIN Users    pb ON pb.UserID    = le.PerformedByUserID
      LEFT JOIN Users    cb ON cb.UserID    = le.CreatedByUserID
      WHERE le.LogEntryID = @LogEntryID
    `);
  return result.recordset[0] || null;
}

async function create(data, auditContext = {}) {
  const {
    siteID, logTypeID, entryDate, performedBy, performedByUserID,
    subject, description, notes, isAutoGenerated = 0, createdByUserID,
  } = data;

  const pool = await getPool();
  const result = await pool.request()
    .input('SiteID',             sql.Int,              siteID)
    .input('LogTypeID',          sql.Int,              logTypeID           || null)
    .input('EntryDate',          sql.DateTime2,        entryDate ? new Date(entryDate) : new Date())
    .input('PerformedBy',        sql.NVarChar(200),    performedBy         || null)
    .input('PerformedByUserID',  sql.Int,              performedByUserID   || null)
    .input('Subject',            sql.NVarChar(500),    subject             || null)
    .input('Description',        sql.NVarChar(sql.MAX), description        || null)
    .input('Notes',              sql.NVarChar(sql.MAX), notes              || null)
    .input('IsAutoGenerated',    sql.Bit,              isAutoGenerated ? 1 : 0)
    .input('CreatedByUserID',    sql.Int,              createdByUserID || auditContext.userID || null)
    .query(`
      INSERT INTO LogEntries
        (SiteID, LogTypeID, EntryDate, PerformedBy, PerformedByUserID,
         Subject, Description, Notes, IsAutoGenerated, CreatedByUserID)
      VALUES
        (@SiteID, @LogTypeID, @EntryDate, @PerformedBy, @PerformedByUserID,
         @Subject, @Description, @Notes, @IsAutoGenerated, @CreatedByUserID);
      SELECT SCOPE_IDENTITY() AS NewID
    `);

  const newID = result.recordset[0].NewID;
  await writeAudit({
    tableName: 'LogEntries', recordID: newID, action: 'INSERT',
    newValues: data,
    userID: auditContext.userID, ip: auditContext.ip, userAgent: auditContext.userAgent,
  });
  return getByID(newID);
}

async function update(logEntryID, data, auditContext = {}) {
  const {
    siteID, logTypeID, entryDate, performedBy, performedByUserID,
    subject, description, notes,
  } = data;

  const pool = await getPool();
  const old  = await getByID(logEntryID);

  await pool.request()
    .input('LogEntryID',        sql.Int,              logEntryID)
    .input('SiteID',            sql.Int,              siteID              || null)
    .input('LogTypeID',         sql.Int,              logTypeID           || null)
    .input('EntryDate',         sql.DateTime2,        entryDate ? new Date(entryDate) : null)
    .input('PerformedBy',       sql.NVarChar(200),    performedBy         || null)
    .input('PerformedByUserID', sql.Int,              performedByUserID   || null)
    .input('Subject',           sql.NVarChar(500),    subject             || null)
    .input('Description',       sql.NVarChar(sql.MAX), description        || null)
    .input('Notes',             sql.NVarChar(sql.MAX), notes              || null)
    .query(`
      UPDATE LogEntries SET
        SiteID            = @SiteID,
        LogTypeID         = @LogTypeID,
        EntryDate         = @EntryDate,
        PerformedBy       = @PerformedBy,
        PerformedByUserID = @PerformedByUserID,
        Subject           = @Subject,
        Description       = @Description,
        Notes             = @Notes
      WHERE LogEntryID = @LogEntryID
    `);

  await writeAudit({
    tableName: 'LogEntries', recordID: logEntryID, action: 'UPDATE',
    oldValues: old, newValues: data,
    userID: auditContext.userID, ip: auditContext.ip, userAgent: auditContext.userAgent,
  });
  return getByID(logEntryID);
}

async function hardDelete(logEntryID, auditContext = {}) {
  const pool = await getPool();
  const old  = await getByID(logEntryID);

  await pool.request()
    .input('LogEntryID', sql.Int, logEntryID)
    .query('DELETE FROM LogEntries WHERE LogEntryID = @LogEntryID');

  await writeAudit({
    tableName: 'LogEntries', recordID: logEntryID, action: 'DELETE',
    oldValues: old,
    userID: auditContext.userID, ip: auditContext.ip, userAgent: auditContext.userAgent,
  });
}

const SORT_COLUMNS = {
  date:        'le.EntryDate',
  site:        's.SiteName',
  type:        'lt.TypeName',
  subject:     'le.Subject',
  performedBy: 'le.PerformedBy',
  createdAt:   'le.CreatedAt',
};

async function getAll({ siteID, logTypeID, dateFrom, dateTo, search, sort = 'date', dir = 'desc', page = 1, pageSize = 25 } = {}) {
  const pool = await getPool();
  const req  = pool.request();
  const conditions = [];

  if (siteID) {
    conditions.push('le.SiteID = @SiteID');
    req.input('SiteID', sql.Int, siteID);
  }
  if (logTypeID) {
    conditions.push('le.LogTypeID = @LogTypeID');
    req.input('LogTypeID', sql.Int, logTypeID);
  }
  if (dateFrom) {
    conditions.push('le.EntryDate >= @DateFrom');
    req.input('DateFrom', sql.Date, new Date(dateFrom));
  }
  if (dateTo) {
    conditions.push('le.EntryDate <= @DateTo');
    req.input('DateTo', sql.Date, new Date(dateTo));
  }
  if (search) {
    conditions.push('(le.Subject LIKE @Search OR le.PerformedBy LIKE @Search OR s.SiteName LIKE @Search)');
    req.input('Search', sql.NVarChar(200), `%${search}%`);
  }

  const where    = conditions.length ? 'WHERE ' + conditions.join(' AND ') : '';
  const orderCol = SORT_COLUMNS[sort] || 'le.EntryDate';
  const orderDir = dir === 'asc' ? 'ASC' : 'DESC';
  const offset   = (page - 1) * pageSize;
  req.input('Offset',   sql.Int, offset);
  req.input('PageSize', sql.Int, pageSize);

  const countReq = pool.request();
  if (siteID)    countReq.input('SiteID',    sql.Int,         siteID);
  if (logTypeID) countReq.input('LogTypeID', sql.Int,         logTypeID);
  if (dateFrom)  countReq.input('DateFrom',  sql.Date,        new Date(dateFrom));
  if (dateTo)    countReq.input('DateTo',    sql.Date,        new Date(dateTo));
  if (search)    countReq.input('Search',    sql.NVarChar(200), `%${search}%`);

  const countResult = await countReq.query(`
    SELECT COUNT(*) AS Total
    FROM LogEntries le
    LEFT JOIN Sites s ON s.SiteID = le.SiteID
    ${where}
  `);
  const total = countResult.recordset[0].Total;

  const result = await req.query(`
    SELECT
      le.LogEntryID, le.SiteID, le.LogTypeID, le.EntryDate,
      le.PerformedBy, le.PerformedByUserID, le.Subject,
      le.IsAutoGenerated, le.CreatedAt, le.CreatedByUserID,
      CASE WHEN s.ParentSiteID IS NOT NULL
           THEN ps.SiteName + ' / ' + s.SiteName
           ELSE s.SiteName END AS SiteName,
      lt.TypeName    AS LogTypeName,
      pb.DisplayName AS PerformedByUserName,
      cb.DisplayName AS CreatedByName
    FROM LogEntries le
    LEFT JOIN Sites    s  ON s.SiteID    = le.SiteID
    LEFT JOIN Sites    ps ON ps.SiteID   = s.ParentSiteID
    LEFT JOIN LogTypes lt ON lt.LogTypeID = le.LogTypeID
    LEFT JOIN Users    pb ON pb.UserID   = le.PerformedByUserID
    LEFT JOIN Users    cb ON cb.UserID   = le.CreatedByUserID
    ${where}
    ORDER BY ${orderCol} ${orderDir}, le.LogEntryID DESC
    OFFSET @Offset ROWS FETCH NEXT @PageSize ROWS ONLY
  `);

  return { rows: result.recordset, total, page, pageSize, totalPages: Math.ceil(total / pageSize) };
}

module.exports = { getAll, getBySite, getByID, create, update, delete: hardDelete };
