'use strict';

const { getPool, sql } = require('../config/database');
const { writeAudit }   = require('./auditModel');
const inventoryModel   = require('./inventoryModel');

async function getCurrentItems(siteID) {
  const pool = await getPool();
  const result = await pool.request()
    .input('SiteID', sql.Int, siteID)
    .query(`
      SELECT
        si.SiteInventoryID, si.SiteID, si.ItemID, si.Quantity,
        si.InstalledAt, si.InstalledByUserID, si.InstallNotes, si.PulledFromLocationID,
        si.RemovedAt,   si.RemovedByUserID,   si.RemovalNotes,
        si.InstallLogEntryID, si.RemovalLogEntryID,
        i.TrackingType, i.SerialNumber, i.CommonName, i.ModelNumber, i.Manufacturer,
        c.CategoryName,
        s.StatusName,
        ib.DisplayName AS InstalledByName,
        pl.LocationName AS PulledFromLocationName
      FROM SiteInventory si
      JOIN Inventory           i  ON i.ItemID      = si.ItemID
      LEFT JOIN InventoryCategories c  ON c.CategoryID  = i.CategoryID
      LEFT JOIN InventoryStatuses   s  ON s.StatusID    = i.StatusID
      LEFT JOIN Users               ib ON ib.UserID     = si.InstalledByUserID
      LEFT JOIN StockLocations      pl ON pl.LocationID = si.PulledFromLocationID
      WHERE si.SiteID    = @SiteID
        AND si.RemovedAt IS NULL
      ORDER BY si.InstalledAt DESC
    `);

  // Combine multiple install records for the same bulk item into one display row
  const rows = result.recordset;
  const serialized = rows.filter(r => r.TrackingType !== 'bulk');
  const bulkMap = new Map();
  rows.filter(r => r.TrackingType === 'bulk').forEach(r => {
    if (bulkMap.has(r.ItemID)) {
      bulkMap.get(r.ItemID).Quantity += r.Quantity;
    } else {
      bulkMap.set(r.ItemID, { ...r });
    }
  });

  return [...serialized, ...bulkMap.values()]
    .sort((a, b) => new Date(b.InstalledAt) - new Date(a.InstalledAt));
}

async function getHistory(siteID) {
  const pool = await getPool();
  const result = await pool.request()
    .input('SiteID', sql.Int, siteID)
    .query(`
      SELECT
        si.SiteInventoryID, si.SiteID, si.ItemID,
        si.InstalledAt, si.InstalledByUserID, si.InstallNotes, si.PulledFromLocationID,
        si.RemovedAt,   si.RemovedByUserID,   si.RemovalNotes,
        si.InstallLogEntryID, si.RemovalLogEntryID,
        i.SerialNumber, i.ModelNumber, i.Manufacturer,
        c.CategoryName,
        ib.DisplayName AS InstalledByName,
        rb.DisplayName AS RemovedByName,
        pl.LocationName AS PulledFromLocationName
      FROM SiteInventory si
      JOIN Inventory           i  ON i.ItemID      = si.ItemID
      LEFT JOIN InventoryCategories c  ON c.CategoryID  = i.CategoryID
      LEFT JOIN Users               ib ON ib.UserID     = si.InstalledByUserID
      LEFT JOIN Users               rb ON rb.UserID     = si.RemovedByUserID
      LEFT JOIN StockLocations      pl ON pl.LocationID = si.PulledFromLocationID
      WHERE si.SiteID = @SiteID
      ORDER BY si.InstalledAt DESC
    `);
  return result.recordset;
}

async function installItem(siteID, itemID, { installedAt, installedByUserID, installNotes, pulledFromLocationID, pulledFromUserID, quantity } = {}, auditContext = {}) {
  const pool = await getPool();

  // Resolve item details for auto-generated log subject and bulk check
  const itemResult = await pool.request()
    .input('ItemID', sql.Int, itemID)
    .query('SELECT SerialNumber, ModelNumber, TrackingType FROM Inventory WHERE ItemID = @ItemID');
  const itemRow     = itemResult.recordset[0] || {};
  const isBulk      = itemRow.TrackingType === 'bulk';
  const installQty  = isBulk ? (parseInt(quantity, 10) || 1) : 1;
  const serialNumber = itemRow.SerialNumber || itemRow.ModelNumber || String(itemID);

  // Resolve the LogTypeID for 'Inventory Change'
  const logTypeResult = await pool.request()
    .input('TypeName', sql.NVarChar(100), 'Inventory Change')
    .query('SELECT LogTypeID FROM LogTypes WHERE TypeName = @TypeName');
  const logTypeID = logTypeResult.recordset[0] ? logTypeResult.recordset[0].LogTypeID : null;

  const installDate = installedAt ? new Date(installedAt) : new Date();

  const tx = new sql.Transaction(pool);
  await tx.begin();

  try {
    // 1. Insert LogEntry
    const logResult = await new sql.Request(tx)
      .input('SiteID',          sql.Int,           siteID)
      .input('LogTypeID',       sql.Int,           logTypeID    || null)
      .input('EntryDate',       sql.Date,          installDate)
      .input('Subject',         sql.NVarChar(500), `Item installed: ${serialNumber}`)
      .input('IsAutoGenerated', sql.Bit,           1)
      .input('CreatedByUserID', sql.Int,           installedByUserID || auditContext.userID || null)
      .query(`
        INSERT INTO LogEntries
          (SiteID, LogTypeID, EntryDate, Subject, IsAutoGenerated, CreatedByUserID)
        VALUES
          (@SiteID, @LogTypeID, @EntryDate, @Subject, @IsAutoGenerated, @CreatedByUserID);
        SELECT SCOPE_IDENTITY() AS NewLogID
      `);
    const installLogEntryID = logResult.recordset[0].NewLogID;

    // 2. Insert SiteInventory
    const siResult = await new sql.Request(tx)
      .input('SiteID',              sql.Int,            siteID)
      .input('ItemID',              sql.Int,            itemID)
      .input('Quantity',            sql.Int,            installQty)
      .input('InstalledAt',         sql.DateTime2,      installDate)
      .input('InstalledByUserID',   sql.Int,            installedByUserID   || null)
      .input('InstallNotes',        sql.NVarChar(sql.MAX), installNotes     || null)
      .input('PulledFromLocationID', sql.Int,            pulledFromLocationID || null)
      .input('PulledFromUserID',     sql.Int,            pulledFromUserID     || null)
      .input('InstallLogEntryID',    sql.Int,            installLogEntryID)
      .query(`
        INSERT INTO SiteInventory
          (SiteID, ItemID, Quantity, InstalledAt, InstalledByUserID, InstallNotes,
           PulledFromLocationID, PulledFromUserID, InstallLogEntryID)
        VALUES
          (@SiteID, @ItemID, @Quantity, @InstalledAt, @InstalledByUserID, @InstallNotes,
           @PulledFromLocationID, @PulledFromUserID, @InstallLogEntryID);
        SELECT SCOPE_IDENTITY() AS NewSIID
      `);
    const newSiteInventoryID = siResult.recordset[0].NewSIID;

    // 3. For serialized items: mark as Deployed, clear location.
    //    For bulk items: leave status alone (tracked by quantity math).
    if (!isBulk) {
      const statusResult = await new sql.Request(tx)
        .input('StatusName', sql.NVarChar(50), 'Deployed')
        .query('SELECT StatusID FROM InventoryStatuses WHERE StatusName = @StatusName');
      const deployedStatusID = statusResult.recordset[0] ? statusResult.recordset[0].StatusID : null;

      await new sql.Request(tx)
        .input('ItemID',   sql.Int, itemID)
        .input('StatusID', sql.Int, deployedStatusID || null)
        .query(`
          UPDATE Inventory SET
            StatusID         = @StatusID,
            StockLocationID  = NULL,
            AssignedToUserID = NULL
          WHERE ItemID = @ItemID
        `);
    }

    await tx.commit();

    // For bulk items, decrease the stock pool the units came from
    if (isBulk && (pulledFromLocationID || pulledFromUserID)) {
      await inventoryModel.adjustStock(itemID, pulledFromLocationID || null, pulledFromUserID || null, -installQty);
    }

    await writeAudit({
      tableName: 'SiteInventory', recordID: newSiteInventoryID, action: 'INSTALL',
      newValues: { siteID, itemID, installedAt, installedByUserID, installNotes, pulledFromLocationID, pulledFromUserID },
      userID: auditContext.userID, ip: auditContext.ip, userAgent: auditContext.userAgent,
    });

    return newSiteInventoryID;
  } catch (err) {
    await tx.rollback();
    throw err;
  }
}

async function removeItem(siteInventoryID, { removedAt, removedByUserID, removalNotes } = {}, auditContext = {}) {
  const pool = await getPool();

  // Fetch the SiteInventory row to get SiteID, ItemID, and serial number
  const siResult = await pool.request()
    .input('SiteInventoryID', sql.Int, siteInventoryID)
    .query(`
      SELECT si.SiteID, si.ItemID, i.SerialNumber, i.TrackingType
      FROM SiteInventory si
      JOIN Inventory i ON i.ItemID = si.ItemID
      WHERE si.SiteInventoryID = @SiteInventoryID
    `);

  if (!siResult.recordset.length) {
    throw new Error(`SiteInventory record not found: ${siteInventoryID}`);
  }

  const { SiteID: siteID, ItemID: itemID, SerialNumber: serialNumber, TrackingType: trackingType } = siResult.recordset[0];

  // Resolve LogTypeID for 'Inventory Change'
  const logTypeResult = await pool.request()
    .input('TypeName', sql.NVarChar(100), 'Inventory Change')
    .query('SELECT LogTypeID FROM LogTypes WHERE TypeName = @TypeName');
  const logTypeID = logTypeResult.recordset[0] ? logTypeResult.recordset[0].LogTypeID : null;

  const removalDate = removedAt ? new Date(removedAt) : new Date();

  const tx = new sql.Transaction(pool);
  await tx.begin();

  try {
    // 1. Insert removal LogEntry
    const logResult = await new sql.Request(tx)
      .input('SiteID',          sql.Int,           siteID)
      .input('LogTypeID',       sql.Int,           logTypeID || null)
      .input('EntryDate',       sql.Date,          removalDate)
      .input('Subject',         sql.NVarChar(500), `Item removed: ${serialNumber || itemID}`)
      .input('IsAutoGenerated', sql.Bit,           1)
      .input('CreatedByUserID', sql.Int,           removedByUserID || auditContext.userID || null)
      .query(`
        INSERT INTO LogEntries
          (SiteID, LogTypeID, EntryDate, Subject, IsAutoGenerated, CreatedByUserID)
        VALUES
          (@SiteID, @LogTypeID, @EntryDate, @Subject, @IsAutoGenerated, @CreatedByUserID);
        SELECT SCOPE_IDENTITY() AS NewLogID
      `);
    const removalLogEntryID = logResult.recordset[0].NewLogID;

    // 2. Update SiteInventory
    await new sql.Request(tx)
      .input('SiteInventoryID',  sql.Int,            siteInventoryID)
      .input('RemovedAt',        sql.DateTime2,      removalDate)
      .input('RemovedByUserID',  sql.Int,            removedByUserID  || null)
      .input('RemovalNotes',     sql.NVarChar(sql.MAX), removalNotes  || null)
      .input('RemovalLogEntryID',sql.Int,            removalLogEntryID)
      .query(`
        UPDATE SiteInventory SET
          RemovedAt         = @RemovedAt,
          RemovedByUserID   = @RemovedByUserID,
          RemovalNotes      = @RemovalNotes,
          RemovalLogEntryID = @RemovalLogEntryID
        WHERE SiteInventoryID = @SiteInventoryID
      `);

    // 3. For serialized items: revert to In-Stock.
    //    For bulk items: leave status alone (tracked by quantity math).
    if (trackingType !== 'bulk') {
      const statusResult = await new sql.Request(tx)
        .input('StatusName', sql.NVarChar(50), 'In-Stock')
        .query('SELECT StatusID FROM InventoryStatuses WHERE StatusName = @StatusName');
      const inStockStatusID = statusResult.recordset[0] ? statusResult.recordset[0].StatusID : null;

      await new sql.Request(tx)
        .input('ItemID',   sql.Int, itemID)
        .input('StatusID', sql.Int, inStockStatusID || null)
        .query(`
          UPDATE Inventory SET
            StatusID        = @StatusID,
            StockLocationID = NULL
          WHERE ItemID = @ItemID
        `);
    }

    await tx.commit();

    await writeAudit({
      tableName: 'SiteInventory', recordID: siteInventoryID, action: 'REMOVE',
      newValues: { siteInventoryID, removedAt, removedByUserID, removalNotes },
      userID: auditContext.userID, ip: auditContext.ip, userAgent: auditContext.userAgent,
    });
  } catch (err) {
    await tx.rollback();
    throw err;
  }
}

async function getItemHistory(itemID) {
  const pool = await getPool();
  const result = await pool.request()
    .input('ItemID', sql.Int, itemID)
    .query(`
      SELECT
        si.SiteInventoryID, si.SiteID, si.ItemID,
        si.InstalledAt, si.RemovedAt, si.InstallNotes, si.RemovalNotes,
        si.InstalledByUserID, si.RemovedByUserID,
        s.SiteName,
        ib.DisplayName AS InstalledByName,
        rb.DisplayName AS RemovedByName
      FROM SiteInventory si
      JOIN Sites s ON s.SiteID = si.SiteID
      LEFT JOIN Users ib ON ib.UserID = si.InstalledByUserID
      LEFT JOIN Users rb ON rb.UserID = si.RemovedByUserID
      WHERE si.ItemID = @ItemID
      ORDER BY si.InstalledAt DESC
    `);
  return result.recordset;
}

// Removes a specific quantity of a bulk item from a site.
// Consumes rows newest-first; fully soft-deletes rows where qty is exhausted,
// partially reduces the quantity on rows where only some units are removed.
async function removeBulkQuantity(siteID, itemID, removeQty, { removedByUserID } = {}, auditContext = {}) {
  const pool = await getPool();

  const siRows = await pool.request()
    .input('SiteID', sql.Int, siteID)
    .input('ItemID', sql.Int, itemID)
    .query(`
      SELECT si.SiteInventoryID, si.Quantity
      FROM SiteInventory si
      WHERE si.SiteID = @SiteID AND si.ItemID = @ItemID AND si.RemovedAt IS NULL
      ORDER BY si.InstalledAt DESC
    `);

  const totalInstalled = siRows.recordset.reduce((sum, r) => sum + r.Quantity, 0);
  if (removeQty > totalInstalled) {
    const err = new Error(`Cannot remove ${removeQty} — only ${totalInstalled} currently installed.`);
    err.userMessage = err.message;
    throw err;
  }

  let remaining = removeQty;
  for (const row of siRows.recordset) {
    if (remaining <= 0) break;
    if (row.Quantity <= remaining) {
      await removeItem(row.SiteInventoryID, { removedByUserID }, auditContext);
      remaining -= row.Quantity;
    } else {
      // Partial reduction — just lower the quantity, no full removal
      await pool.request()
        .input('SiteInventoryID', sql.Int, row.SiteInventoryID)
        .input('NewQuantity',     sql.Int, row.Quantity - remaining)
        .query('UPDATE SiteInventory SET Quantity = @NewQuantity WHERE SiteInventoryID = @SiteInventoryID');
      remaining = 0;
    }
  }
}

async function getByID(siteInventoryID) {
  const pool = await getPool();
  const result = await pool.request()
    .input('SiteInventoryID', sql.Int, siteInventoryID)
    .query(`
      SELECT si.SiteInventoryID, si.SiteID, si.ItemID, si.Quantity,
             i.SerialNumber, i.ModelNumber, i.Manufacturer, i.TrackingType
      FROM SiteInventory si
      JOIN Inventory i ON i.ItemID = si.ItemID
      WHERE si.SiteInventoryID = @SiteInventoryID
    `);
  return result.recordset[0] || null;
}

module.exports = { getCurrentItems, getHistory, getItemHistory, getByID, installItem, removeItem, removeBulkQuantity };
